services:
  postgres:
    image: postgres:16-alpine
    container_name: profecia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: profecia
      POSTGRES_PASSWORD: profecia
      POSTGRES_DB: profecia
    # ports:
    #   - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U profecia -d profecia"]
      interval: 5s
      timeout: 3s
      retries: 20

  #  build vai sempre dar merda. dar build localmente:
  # mkdir -p blockchain_program/target/deploy
  # cp PRIVATE_KEY/*.json /workspace/target/deploy/blockchain_program-keypair.json
  # cargo build-sbf
  # blockchain-program:
  #   build:
  #     context: ./backend
  #     dockerfile: blockchain_program/Dockerfile
  #   container_name: profecia-blockchain-program
  #   volumes:
  #     - ./data/program-so:/program/so
  #     - ./data/program-keys:/program/keys

  surfpool:
    image: surfpool/surfpool
    container_name: surfpool-instance
    # ports:
    # - "8899:8899"
    # - "8900:8900"
    # - "18488:18488"
    volumes:
      - ./backend/blockchain_program:/workspace
      - ./backend/blockchain_program/PRIVATE_KEY/id.json:/root/.config/solana/id.json:ro
    command: start --no-tui
    restart: unless-stopped
    # depends_on:
    #   blockchain-program:
    #     condition: service_completed_successfully

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: profecia-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://profecia:profecia@postgres:5432/profecia
      RPC_URL: http://surfpool:8899
      EXTERNAL_RPC_URL: ${EXTERNAL_RPC_URL}
      RUST_LOG: info
      ADMIN_WALLET_PATH: /app/admin-wallet.json
    volumes:
      - ./backend/blockchain_program/PRIVATE_KEY/id.json:/app/admin-wallet.json:ro
    depends_on:
      postgres:
        condition: service_healthy
      surfpool:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: profecia-frontend
    restart: unless-stopped
    environment:
      BACKEND_URL: http://backend:3000
      ORIGIN: ${ORIGIN}
      PORT: "3000"
      NODE_ENV: production
    depends_on:
      - backend

  rpxy:
    image: jqtype/rpxy:latest
    container_name: profecia-rpxy
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    environment:
      - LOG_LEVEL=warn
    volumes:
      - ./rpxy/config/config.toml:/etc/rpxy.toml:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    environment:
      - TUNNEL_TOKEN
    command: "tunnel run"
    depends_on:
      - frontend
    restart: unless-stopped
